# Generated by Django 3.2.2 on 2021-06-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_rubric_test_test_set'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('order', 'test_set')},
        ),
    ]
